In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv('Iris.csv')
dataset.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
dataset

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [5]:
dataset['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [6]:
dataset['Species'].replace({'Iris-setosa' : '1', 'Iris-versicolor' :'2', 'Iris-virginica' : '3'} , inplace=True)

In [7]:
dataset

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm Species
0      1            5.1           3.5            1.4           0.2       1
1      2            4.9           3.0            1.4           0.2       1
2      3            4.7           3.2            1.3           0.2       1
3      4            4.6           3.1            1.5           0.2       1
4      5            5.0           3.6            1.4           0.2       1
..   ...            ...           ...            ...           ...     ...
145  146            6.7           3.0            5.2           2.3       3
146  147            6.3           2.5            5.0           1.9       3
147  148            6.5           3.0            5.2           2.0       3
148  149            6.2           3.4            5.4           2.3       3
149  150            5.9           3.0            5.1           1.8       3

[150 rows x 6 columns]

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train , X_test , y_train, y_test =train_test_split(dataset[['SepalLengthCm' ,'SepalWidthCm' ,'PetalLengthCm', 'PetalWidthCm']], dataset['Species'] , 
                 test_size=0.2)

In [10]:
len(X_train)

120

In [11]:
len(X_test)

30

In [12]:
from sklearn.linear_model import LogisticRegression

In [13]:
lr=LogisticRegression()

In [14]:
lr.fit(X_train , y_train)

C:\Users\bmbar\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [16]:
X_test

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
147            6.5           3.0            5.2           2.0
70             5.9           3.2            4.8           1.8
16             5.4           3.9            1.3           0.4
37             4.9           3.1            1.5           0.1
111            6.4           2.7            5.3           1.9
144            6.7           3.3            5.7           2.5
44             5.1           3.8            1.9           0.4
39             5.1           3.4            1.5           0.2
13             4.3           3.0            1.1           0.1
113            5.7           2.5            5.0           2.0
110            6.5           3.2            5.1           2.0
112            6.8           3.0            5.5           2.1
29             4.7           3.2            1.6           0.2
60             5.0           2.0            3.5           1.0
96             5.7           2.9            4.2           1.3
1              4.9           3.0            1.4           0.2
62             6.0           2.2            4.0           1.0
94             5.6           2.7            4.2           1.3
139            6.9           3.1            5.4           2.1
131            7.9           3.8            6.4           2.0
98             5.1           2.5            3.0           1.1
57             4.9           2.4            3.3           1.0
145            6.7           3.0            5.2           2.3
114            5.8           2.8            5.1           2.4
12             4.8           3.0            1.4           0.1
97             6.2           2.9            4.3           1.3
27             5.2           3.5            1.5           0.2
104            6.5           3.0            5.8           2.2
34             4.9           3.1            1.5           0.1
68             6.2           2.2            4.5           1.5

In [15]:
lr.predict(X_test)

array(['3', '3', '1', '1', '3', '3', '1', '1', '1', '3', '3', '3', '1',
       '2', '2', '1', '2', '2', '3', '3', '2', '2', '3', '3', '1', '2',
       '1', '3', '1', '2'], dtype=object)

In [20]:
X_test

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
94             5.6           2.7            4.2           1.3
107            7.3           2.9            6.3           1.8
72             6.3           2.5            4.9           1.5
46             5.1           3.8            1.6           0.2
42             4.4           3.2            1.3           0.2
50             7.0           3.2            4.7           1.4
29             4.7           3.2            1.6           0.2
129            7.2           3.0            5.8           1.6
116            6.5           3.0            5.5           1.8
64             5.6           2.9            3.6           1.3
103            6.3           2.9            5.6           1.8
17             5.1           3.5            1.4           0.3
119            6.0           2.2            5.0           1.5
71             6.1           2.8            4.0           1.3
38             4.4           3.0            1.3           0.2
80             5.5           2.4            3.8           1.1
105            7.6           3.0            6.6           2.1
97             6.2           2.9            4.3           1.3
49             5.0           3.3            1.4           0.2
85             6.0           3.4            4.5           1.6
124            6.7           3.3            5.7           2.1
90             5.5           2.6            4.4           1.2
138            6.0           3.0            4.8           1.8
141            6.9           3.1            5.1           2.3
21             5.1           3.7            1.5           0.4
66             5.6           3.0            4.5           1.5
57             4.9           2.4            3.3           1.0
140            6.7           3.1            5.6           2.4
12             4.8           3.0            1.4           0.1
54             6.5           2.8            4.6           1.5

In [21]:
lr.score(X_test, y_test)

1.0